<a href="https://colab.research.google.com/github/Bhairavi-shah/AbstractiveUserReviewConsolidation/blob/master/Module2.2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
%%time
from google.colab import drive
drive.mount('/content/gdrive')

import pandas as pd
import nltk
from nltk.corpus import stopwords
from  nltk.stem import SnowballStemmer
import re

df = pd.read_csv(F"/content/gdrive/My Drive/PROJECT | S7-S8/Data/training.csv", engine='python', 
                  names=["target", "ids", "date", "flag", "user", "text"])

pd.set_option('display.max_colwidth',1000)
nltk.download('stopwords')
stop_words = stopwords.words("english")
stemmer = SnowballStemmer("english")

# TEXT CLEANING
TEXT_CLEANING_RE = "@\S+|https?:\S+|http?:\S|[^A-Za-z0-9]+"

def preprocess(text, stem=False):
    # Remove link,user and special characters
    text = re.sub(TEXT_CLEANING_RE, ' ', str(text).lower()).strip()
    tokens = []
    for token in text.split():
        if token not in stop_words:
            if stem:
                tokens.append(stemmer.stem(token))
            else:
                tokens.append(token)
    return " ".join(tokens)

df['PreprocessedText'] = df.text.apply(lambda x: preprocess(x))
print(df)


Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
         target  ...                                                       PreprocessedText
0             0  ...                           awww bummer shoulda got david carr third day
1             0  ...  upset update facebook texting might cry result school today also blah
2             0  ...                   dived many times ball managed save 50

In [0]:
import pandas as pd
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
import nltk
nltk.download('punkt')

# Creating the Bag of Words model 
word2count = {}
for data in df['PreprocessedText'].values: 
    words = nltk.word_tokenize(data) 
    for word in words: 
        if word not in word2count.keys(): 
            word2count[word] = 1
        else: 
            word2count[word] += 1

print(word2count["like"], word2count["hate"])

# Split target column
#y = df[['target']]
#df_traintest = df[['PreprocessedText']]

# create training and testing vars
#X_train, X_test, y_train, y_test = train_test_split(df_traintest, y, test_size=0.05)
#print(X_train.shape, y_train.shape)
#print(X_test.shape, y_test.shape)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
78567 19821


In [4]:
%%time
import heapq
freq_words = heapq.nlargest(50, word2count, key=word2count.get)

X = [] 
i = 0
for data in df['PreprocessedText'].values: 
    vector = []
    for word in freq_words: 
        if word in nltk.word_tokenize(data): 
            vector.append(1) 
        else: 
            vector.append(0) 
    i+=1
    print(i)
    X.append(vector)


Streaming output truncated to the last 5000 lines.
1595002
1595003
1595004
1595005
1595006
1595007
1595008
1595009
1595010
1595011
1595012
1595013
1595014
1595015
1595016
1595017
1595018
1595019
1595020
1595021
1595022
1595023
1595024
1595025
1595026
1595027
1595028
1595029
1595030
1595031
1595032
1595033
1595034
1595035
1595036
1595037
1595038
1595039
1595040
1595041
1595042
1595043
1595044
1595045
1595046
1595047
1595048
1595049
1595050
1595051
1595052
1595053
1595054
1595055
1595056
1595057
1595058
1595059
1595060
1595061
1595062
1595063
1595064
1595065
1595066
1595067
1595068
1595069
1595070
1595071
1595072
1595073
1595074
1595075
1595076
1595077
1595078
1595079
1595080
1595081
1595082
1595083
1595084
1595085
1595086
1595087
1595088
1595089
1595090
1595091
1595092
1595093
1595094
1595095
1595096
1595097
1595098
1595099
1595100
1595101
1595102
1595103
1595104
1595105
1595106
1595107
1595108
1595109
1595110
1595111
1595112
1595113
1595114
1595115
1595116
1595117
1595118
1595119
15951

NameError: ignored

In [0]:
import numpy as np
X = np.asarray(X)

In [6]:
print(X)

[[0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [0]:
%%time
#fit a model
from sklearn.ensemble import RandomForestClassifier

text_classifier = RandomForestClassifier(n_estimators=100, random_state=0)
text_classifier.fit(X_train, y_train.values.ravel())

CPU times: user 9min 30s, sys: 5.88 s, total: 9min 36s
Wall time: 9min 36s


In [0]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train.values.ravel())
print("Score Linear Regression     :", lr.score(X_test, y_test.values.ravel()))


Score Linear Regression     : 0.0001881855762279061


In [0]:
%%time
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=25)
knn.fit(X_train, y_train.values.ravel())
print("Score KNeighbors            :", knn.score(X_test, y_test.values.ravel()))

Score KNeighbors            : 0.665175
CPU times: user 11.9 s, sys: 15.6 ms, total: 11.9 s
Wall time: 11.9 s


In [0]:
%%time
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(random_state=0)
dt.fit(X_train, y_train.values.ravel())
print("Score DecisionTree            :", dt.score(X_test, y_test.values.ravel()))

Score DecisionTree            : 0.6231375
CPU times: user 10.3 s, sys: 11.7 ms, total: 10.3 s
Wall time: 10.4 s


In [0]:
%%time 
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=0)
rf.fit(X_train, y_train.values.ravel())
print("Score Random Forest         :", rf.score(X_test, y_test.values.ravel()))

Score Random Forest         : 0.6245
CPU times: user 9min 40s, sys: 5.08 s, total: 9min 45s
Wall time: 9min 45s


In [0]:
from sklearn import svm
supportvm = svm.SVC() 
supportvm.fit(X_train, y_train.values.ravel())
print("Score Support Vector Machine:", supportvm.score(X_test, y_test.values.ravel()))

In [0]:
print("H")

In [0]:
%%time
from sklearn.ensemble import RandomForestClassifier, BaggingClassifier
from sklearn.neighbors import KNeighborsClassifier

# Create the model
knn = KNeighborsClassifier(n_neighbors=3)
bagging = BaggingClassifier(KNeighborsClassifier(), max_samples=0.5, max_features=0.5)

# Fit the model on the training data
knn.fit(X_train, y_train.values.ravel())
bagging.fit(X_train, y_train.values.ravel())

# Evaluate the model
#mae = np.mean(abs(predictions - y_test))
#print('Gradient Boosted Performance on the test set: MAE = %0.4f' % mae)

# Score
print("Score KNeighbors            :", knn.score(X_test, y_test.values.ravel()))
print("Score Bagging               :", bagging.score(X_test, y_test.values.ravel()))



In [0]:
predictions = text_classifier.predict(X_test)
print(predictions)

[4 4 4 ... 4 0 4]


In [0]:
# Score
print("Score:", text_classifier.score(X_test, y_test))


Score: 0.623409375


In [0]:
# Score
print("Score:", text_classifier.score(X_test, y_test))

Score: 0.6244625


In [0]:
df_test = pd.read_json(r"/content/gdrive/My Drive/PROJECT | S7-S8/Data/B0014F7B98.json", lines = True)

print(df)
print(df_test)
"""
target: the polarity of the tweet (0 = negative, 2 = neutral, 4 = positive)
ids: The id of the tweet ( 2087)
date: the date of the tweet (Sat May 16 23:58:44 UTC 2009)
flag: The query (lyx). If there is no query, then this value is NO_QUERY.
user: the user that tweeted (robotickilldozr)
text: the text of the tweet (Lyx is cool)
"""
for column in df.columns:
  print(column)

for column in df_test.columns:
  print(column)


         target  ...                                                       PreprocessedText
0             0  ...                           awww bummer shoulda got david carr third day
1             0  ...  upset update facebook texting might cry result school today also blah
2             0  ...                   dived many times ball managed save 50 rest go bounds
3             0  ...                                       whole body feels itchy like fire
4             0  ...                                                       behaving mad see
...         ...  ...                                                                    ...
1599995       4  ...                                          woke school best feeling ever
1599996       4  ...                               thewdb com cool hear old walt interviews
1599997       4  ...                                        ready mojo makeover ask details
1599998       4  ...                   happy 38th birthday boo alll time tupac a